### ISSUE TITLE
Code block syntax highlighting

### ISSUE THREAD

**Issue by ryanatkn** [svelte-society/recipes-mvp#26]
A number of code blocks in the recipes don't have a language assigned to them or are incorrectly labeled, like JS instead of Svelte/HTML.

On GitHub it looks like "```svelte" works, probably as an alias of HTML. Is it safe to assume that will work for the final published versions of the rendered markdown?

```svelte
<script>
  const one = 1;
  console.log('pretty colors?! somewhat.');
</script>

<div>neat</div>

<style>
  div {
    color: red;
  }
</style>
```

Anyone want to go into a trance and update everything? I'm volunteering too.

**Comment by swyxio** [comment]
ha, nice one. probably a good call to do when we eventually publish

**Comment by ryanatkn** [comment]
Turns out I was wrong and GitHub has support for Svelte. I guess I could have tested that above.

```svelte
<ol>
	{#each things as thing, i}
		the colors
	{/each}
</ol>
```

sad html
```html
<ol>
	{#each things as thing, i}
		the colors
	{/each}
</ol>
```

**Comment by swyxio** [comment]
thats awesome. btw a few months ago i found out that lang detection is an oss repo anyone can contribute to https://twitter.com/swyx/status/1209520989647687680

**Comment by kevmodrome** [comment]
This is dope!

**Comment by ryanatkn** [comment]
Thanks @umanghome for making [the PR to add Svelte to GitHub's syntax](https://github.com/github/linguist/pull/4504)! 🧡
