### ISSUE TITLE
[Reactivity: each blocks] from svelte version 3.23.1 onwards this recipe no longer applies

### ISSUE THREAD

**Issue by opensas** [svelte-society/recipes-mvp#36]
## Reactivity: each blocks

[Reactivity recipe, each blocks section](https://github.com/svelte-society/recipes-mvp/blob/master/language.md#each-blocks) says the following:

> Only assignments to array items that are objects or arrays result in the array itself updating. If the array items are primitives, the change is not traced back to the original array. This is because Svelte only reassigns the actual array items and primitives are passed by value in javascript, not by reference.

From svelte version 3.23.1 this is no loger true:

See this [repl running on svelte 3.23.1](https://svelte.dev/repl/bc170b644f554eb29374138167dea4f0?version=3.23.1), where the issue has been fixed

And this one [running on svelte 3.23.0](https://svelte.dev/repl/bc170b644f554eb29374138167dea4f0?version=3.23.0) where the issue still applies

For context see [svelte issue 4744](https://github.com/sveltejs/svelte/issues/4744)

Proposed modification:

Add a note stating that this section only applies to svelte version lower than 3.23.1 (if you agree with this I can send a pull request)

**Comment by swyxio** [comment]
sure thing! i think also mentioned in https://github.com/svelte-society/recipes-mvp/issues/15#issuecomment-640988008

**Comment by opensas** [comment]
This has already been fixed in https://github.com/svelte-society/recipes-mvp/blob/master/language.md#each-blocks

Closing this issue
