### ISSUE TITLE
EventDispatcher or function as a value? What to use?

### ISSUE THREAD

**Issue by frederikhors** [svelte-society/recipes-mvp#38]
Reading the code on this amazing Modal example: https://svelte.dev/examples#modal I'm trying to understand what's the difference in terms of performances/bundle size/other if I use:

1. `createEventDispatcher()` with directive like `on:close={()=> doSomething()}` or
1. simply pass the function as a value like `action={doSomething}`.

Also in the first case I can't use `on:close={...}` on the `slot`s, right?

If I try it gives me this error: `[!] (plugin svelte) ValidationError: <slot> cannot have directives`

**What do you recommend to use?**

**Comment by babycourageous** [comment]
I always thought as far as choosing between the two it comes down to preference. I find option 1 more "Svelte-y" and option 2 more "React-y".

I don't know if there are any performance/bundle size advantages to either though.

**Comment by swyxio** [comment]
i doubt it matters, i'd just do what the example does

**Comment by babycourageous** [comment]
I'm going to go ahead and close this since it's related more to official Svelte example and personal preference.
