### ISSUE TITLE
Async/await, unmounted components, and bugs

### ISSUE THREAD

**Issue by ryanatkn** [svelte-society/recipes-mvp#6]
I was motivated by the great [`fetch` recipes](https://github.com/svelte-society/recipes-mvp#using-fetch-to-consume-apis-with-svelte) and [this tweet](https://twitter.com/dan_abramov/status/1246432321579950081) from Dan Abramov to look into some of Svelte's behavior for async/await/promises and unmounted components. Everything (minus a potential bug) seemed expected to me, so any bugs are probably the developer's responsibility. Maybe you disagree? I think this is all out of scope for these recipes but it may be useful for later ones.

**tldr**: if a component is unmounted while a promise is pending:

- its reactive assignments and reactive statements with stores are disabled
- its await blocks do what you'd expect and don't render their content (but I think there's a bug with `:then` content being rendered while pending?)
- its events are still triggered
- it can still call callbacks

Here's [the REPL with several examples and discussion](https://svelte.dev/repl/213d51c0a51542478962da4323741fe9?version=3.20.1).

Any thoughts? Any examples or improvements I could add?

In future recipes, it might be helpful to demonstrate some common errors and good patterns and abstractions to fix them. I think Svelte provides all of the tools to do this, so it's mostly about clarifying the pitfalls and their simplest and most ergonomic solutions.

edit: not sure what's up with the assignment to swyx, mabye cause I started with the question template? Also it's not really a question.

**Comment by pngwn** [comment]
This is one of the reasons I always tell people to keep promisey stuff out of components and do it in a store. Components are far easy to reason about when they are just handling/ reacting to plain values.

**Comment by swyxio** [comment]
maybe we should tell people to put async stuff in stores, idk im not that experienced with svelte yet. i think its worth doing.

**Comment by pngwn** [comment]
The only issue with that is that there is a Svelte API for it. I personally don't use `#await` but I know that some people like it.

**Comment by swyxio** [comment]
tradeoffs for everything. i've put this at the end of the fetch recipes - https://github.com/svelte-society/recipes-mvp#using-fetch-to-consume-apis-with-svelte method 4 - @pngwn see if theres anything you'd add regarding that

will be presenting this at the svelte society day in 3 days

**Comment by pngwn** [comment]
@sw-yx sorry for the delayed response but this looks good to me. Great examples to illustrate the idea too.
